apiVersion: v2
name: drone
description: Friends of Drone's Drone Server helm chart
type: application
version: 0.2.0
appVersion: "2.9.1"
kubeVersion: "^1.13.0-0"
home: https://www.drone.io/
keywords:
  - continuous-delivery
  - continuous-deployment
  - continuous-integration
  - docker
  - drone
  - drone.io
  - go
sources:
  - https://github.com/harness/drone
  - https://github.com/FriendsOfDrone/helm-charts
maintainers:
  - name: adnsio
    email: hello@adns.io
  - name: omissis
    email: claudi0.beatric3@gmail.com
