apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drone.fullname" . }}
  labels:
    {{- include "drone.labels" . | nindent 4 }}
type: Opaque
data:
  {{- /*
    Rather than maintain a comprehensive Secret, we map all sub-keys of the "secretEnv" value here.
    This allows for more flexibility and less Chart churn as Drone evolves.
  */}}
  {{- range $envKey, $envVal := .Values.secretEnv }}
  {{ $envKey | upper }}: {{ $envVal | b64enc | quote }}
  {{- end }}
